# Generated by Django 4.1.5 on 2023-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_userinformation_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='abc.jpg', upload_to='images'),
        ),
    ]
