# Generated by Django 4.1.5 on 2023-02-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Image',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('ingredient', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=50000)),
                ('image', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='Images'),
        ),
    ]
